I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 38, in script
    ct "11:58"
Exception: Sayer 'ct' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 38, in script
    ct "11:58"
  File "C:\Users\sharo\Desktop\VN\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\sharo\Desktop\VN\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\sharo\Desktop\VN\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'ct' is not defined.

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.4.24120703
20th Life 1.0
Mon Dec 30 19:47:13 2024
